src/app/__init__.py
import os
import os
from flask_sqlalchemy import SQLAlchemy
from flask import Flask
from flask_session import Session
import redis
import torch
from facenet_pytorch import InceptionResnetV1
import cv2

from models.face_recognition.portaai_fr.classifier import FaceRecognitionClassifier

device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
print('Running on device: {}'.format(device))

facenet_model = "vggface2"
workers = 0 if os.name == 'nt' else 4

classifier = FaceRecognitionClassifier()
resnet = InceptionResnetV1(pretrained=facenet_model).eval().to(device)

cap = cv2.VideoCapture(0)


db = SQLAlchemy()
sess = Session()

def create_app(test_config=None):
    # create and configure the app
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_mapping(
        SECRET_KEY='dev',
        SQLALCHEMY_DATABASE_URI="postgresql://portaai_user:portaai_password@db:5432/portaai_db",
        SQLALCHEMY_TRACK_MODIFICATIONS=False,
        SQLALCHEMY_ECHO=False,
        SESSION_TYPE="redis",
        SESSION_PERMANENT=True,
        SESSION_USE_SIGNER=True,
        SESSION_REDIS=redis.from_url('redis://redis:6379'),
        PERMANENT_SESSION_LIFETIME=86400, 
    )

    if test_config is None:
        # load the instance config, if it exists, when not testing
        app.config.from_pyfile('config.py', silent=True)
    else:
        # load the test config if passed in
        app.config.from_mapping(test_config)

    # ensure the instance folder exists
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass  
    
    db.init_app(app)
    from flask_migrate import Migrate
    Migrate(app, db)
    app.config['SESSION_SQLALCHEMY'] = db
    sess.init_app(app)

    from .landing import landing_bp as landing_blueprint
    app.register_blueprint(landing_blueprint)

    from .auth import auth_bp as auth_blueprint
    app.register_blueprint(auth_blueprint)

    from .main import main_bp as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

src/app/landing/__init__.py
from app.landing.views import landing_bp

src/app/landing/views.py
from flask import (
    Blueprint, render_template)
import sys
from flask import redirect, url_for, session
sys.path.append('../')

landing_bp = Blueprint('landing', __name__)

@landing_bp.route('/')
def index():
    if session.get('user_id') is not None:
        return redirect(url_for('main.index'))
    return render_template('landing/index.html')    

src/app/main/__init__.py
from app.main.views import main_bp

src/app/main/views.py
from flask import (
    Blueprint, render_template, request, redirect, url_for, flash, session, Response)
from ..schemas import User, Chat
from app import db, facenet_model, workers, classifier, resnet, cap
from ..auth.views import login_required
from utils.tts_v1 import text_to_speech_v1
import requests
import sys
import os
import json
sys.path.append('../')

from torch.utils.data import DataLoader
from torchvision import datasets
import matplotlib.pyplot as plt
import torch
import cv2
from facenet_pytorch import MTCNN

from models.face_recognition.portaai_fr.get_data import get_files_info
from models.face_recognition.portaai_fr.face_detection import detect_faces_mtcnn
from models.face_recognition.portaai_fr.face_embedding import collate_fn, get_image_embeddings

device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
print('Running on device: {}'.format(device))

main_bp = Blueprint('main', __name__)

data_path = "/portaai/src/data"
num_dirs = len([d for d in os.listdir(data_path) if os.path.isdir(os.path.join(data_path, d))])
print(f"Number of directories in {data_path}: {num_dirs}")

if num_dirs > 1:
    # Get Known Faces
    dataset = datasets.ImageFolder(data_path)
    dataset.idx_to_class = {i:c for c, i in dataset.class_to_idx.items()}
    loader = DataLoader(dataset, collate_fn=collate_fn, num_workers=workers)
    aligned, names = detect_faces_mtcnn(dataset, loader)

    # Get Face Embeddings
    dataset_embeddings = get_image_embeddings(data_path, facenet_model, aligned)
    classifier.train(dataset_embeddings, names)

from flask import Response, stream_with_context

@main_bp.route('/llm', methods=('GET', 'POST'))
@login_required
def index():
    audio_output_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'static')
    newest_chat = Chat.query.filter_by(author_id=session['user_id']).order_by(Chat.id.desc()).first()
    
    if newest_chat:
        chat_title = newest_chat.title
        user_input = newest_chat.user_input
        res = newest_chat.text
    else:
        chat_title = 'audio0'
        user_input = None
        res = None

    if request.method == "POST":
        user_input = request.form['user_input']
        print(f"User input: {user_input}")
        messages = []

        if newest_chat:
            for chat in User.query.get(session['user_id']).chats.all():
                messages.append({"role": "user", "content": chat.user_input})
                messages.append({"role": "assistant", "content": chat.text})

        messages.append({"role": "user", "content": user_input})

        def generate_text():
            try:
                response = requests.post(
                    'http://ollama:11434/api/chat', 
                    json={"messages": messages, "stream": True, "model": "myllama3"},
                    stream=True
                )

                collected_text = ""

                for chunk in response.iter_lines():
                    if chunk:
                        chunk_data = chunk.decode('utf-8')
                        chunk_data = json.loads(chunk_data)["message"]["content"]
                        yield chunk_data
                        collected_text += chunk_data
                chat_title = f"audio{int(User.query.get(session['user_id']).chats.count())}"
                # Save chat to database
                chat = Chat(author_id=session['user_id'], title=chat_title, text=collected_text, user_input=user_input)
                db.session.add(chat)
                db.session.commit()

                # Convert text to speech
                num_chats = User.query.get(session['user_id']).chats.count()
                chat_title = f"audio{int(num_chats) - 1}"
                text_to_speech_v1(collected_text, audio_output_path, chat_title)

            except Exception as e:
                yield f"Error: {str(e)}"

        return Response(stream_with_context(generate_text()), content_type='text/plain')

    return render_template('main/index.html', res=res, user_input=user_input, audio_filename=f"{chat_title}.mp3")



@main_bp.route('/video_feed')
def video_feed():
    def generate():

        mtcnn = MTCNN(
            margin=0, min_face_size=50,
            thresholds=[0.6, 0.7, 0.7], factor=0.709, post_process=True,
            device=device, keep_all=True
        )

        while True:
            ret, frame = cap.read()
            if not ret:
                break

            # Detect faces
            boxes, _ = mtcnn.detect(frame)
            if boxes is not None:
                for box in boxes:
                    # Convert frame to RGB and then to tensor
                    rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                    mg_cropped = mtcnn(rgb_frame)
                    if mg_cropped is not None:
                        mg_cropped = mg_cropped.to(device)
                        img_embedding = resnet(mg_cropped).detach().cpu()
                        prediction, probabilities = classifier.predict(img_embedding[0])
                    
                        color = (0, 255, 0) if probabilities >= 0.6 else (0, 0, 255)
                        cv2.rectangle(frame, 
                                      (int(box[0]), int(box[1])), 
                                      (int(box[2]), int(box[3])), 
                                      color, 
                                      2)
                        cv2.putText(frame, 
                                    f'{prediction} ({probabilities:.2f})', 
                                    (int(box[0]), int(box[1]) - 10), 
                                    cv2.FONT_HERSHEY_SIMPLEX, 
                                    1, 
                                    color, 
                                    2, 
                                    cv2.LINE_AA)
                    

            _, buffer = cv2.imencode('.jpg', frame)
            frame = buffer.tobytes()
            yield (b'--frame\r\n'
                   b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')

    return Response(generate(), mimetype='multipart/x-mixed-replace; boundary=frame')

src/app/schemas/__init__.py
from .user import *
from .chat import *

src/app/templates/base.html
<!doctype html>
<title>portaai - {% block title %}{% endblock %}</title>
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
<link rel="icon" href="{{ url_for('static', filename='images/favicon.ico') }}">

<div class="nav-wrapper">
  <nav>
    <h1>
      <a href="{{ url_for('landing.index') }}">
        portaai 
      </a>
    </h1>
    <ul>
      {% if session.get('user_id') %}
        <li><span>{{ session.get('username') }}</span></li>
        <li><a href="{{ url_for('auth.logout') }}"><svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="#f3f1eb"><path d="M200-120q-33 0-56.5-23.5T120-200v-560q0-33 23.5-56.5T200-840h280v80H200v560h280v80H200Zm440-160-55-58 102-102H360v-80h327L585-622l55-58 200 200-200 200Z"/></svg></a></li>
      {% else %}
        <li><a class="login" href="{{ url_for('auth.register') }}">
          <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="#f3f1eb"><path d="M720-400v-120H600v-80h120v-120h80v120h120v80H800v120h-80Zm-360-80q-66 0-113-47t-47-113q0-66 47-113t113-47q66 0 113 47t47 113q0 66-47 113t-113 47ZM40-160v-112q0-34 17.5-62.5T104-378q62-31 126-46.5T360-440q66 0 130 15.5T616-378q29 15 46.5 43.5T680-272v112H40Zm80-80h480v-32q0-11-5.5-20T580-306q-54-27-109-40.5T360-360q-56 0-111 13.5T140-306q-9 5-14.5 14t-5.5 20v32Zm240-320q33 0 56.5-23.5T440-640q0-33-23.5-56.5T360-720q-33 0-56.5 23.5T280-640q0 33 23.5 56.5T360-560Zm0-80Zm0 400Z"/></svg>
        </a></li>
        <li><a class="login" href="{{ url_for('auth.login') }}">
          <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="#f3f1eb"><path d="M480-120v-80h280v-560H480v-80h280q33 0 56.5 23.5T840-760v560q0 33-23.5 56.5T760-120H480Zm-80-160-55-58 102-102H120v-80h327L345-622l55-58 200 200-200 200Z"/></svg>
        </a></li>
      {% endif %}
    </ul>
  </nav>
</div>

<section class="content">
  <header>
    {% block header %}{% endblock %}
  </header>
  {% for message in get_flashed_messages() %}
    <div class="flash">{{ message }}</div>
  {% endfor %}
  {% block content %}{% endblock %}
</section>

src/app/templates/main/index.html
{% extends 'base.html' %}

{% block header %}
    <h1 class="chat-title"> {% block title %}Doorman LLM{% endblock %}</h1>
{% endblock %}

{% block content %}
    <div class="chat-container">
        <h1>Live Video Feed</h1>
        <img src="{{ url_for('main.video_feed') }}" alt="Video Feed">
    
        <div class="chat-wrapper">
            <form id="chat-gen" class="chat-form" method="post">
                <label for="user_input">Enter an input:</label>
                <input type="text" name="user_input">    
                <input class="chat-button" type="submit" value="Submit">
            </form>
        </div>
    
        <div class="chat-answer"></div>
    
        <audio controls>
            <source src="{{ url_for('static', filename=audio_filename) }}" type="audio/mpeg">
        </audio>
    
        <div id="loading-overlay" style="display: none;">
            <div id="loading-spinner">
                <div class="spinner"></div>
            </div>
            <p class="loading-message">Generating Answer...</p>
        </div>
    </div>

    <script src="{{ url_for('static', filename='script.js') }}"></script>
{% endblock %}